services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lic-mgmt-app
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      PORT: 4000
    restart: unless-stopped
